### ISSUE TITLE
synchronize package

### ISSUE THREAD

**Issue by jincdream** [burkostya/npm-registry#5]
May I ask how to synchronize some public package I need into the registry?

**Comment by burkostya** [comment]
I never did it. So all i can is give you some ideas)
Obvious way is to download packages from public registry and publish them to private one.
Also you can try partial couchdb replication as described [here](http://wiki.apache.org/couchdb/Replication#Named_Document_Replication)

**Comment by burkostya** [comment]
If you find a way please post it here
