### ISSUE TITLE
weird socket hang ups and gateway timeouts

### ISSUE THREAD

**Issue by japel** [burkostya/npm-registry#7]
Hey there,
trying to npm install I get lots of socket hang ups and 504 errors. Then, after a long time, it will eventually start installing stuff.

I started the container as stated in the readme.

Anyone else experiencing something like that? What could be going wrong?

**Comment by japel** [comment]
Its related to this: https://github.com/docker/docker/issues/20910
So I'll close again...

docker-machine restart default
eval $(docker-machine env default)

fixes it...

**Comment by japel** [comment]
I'd like to reopen this.
I manage to get rid of this weird socket hangups (which seem to appear after my machine goes to hibernation) by restarting the docker machine.
The thing is, I lose all the couchdb data (which was mounted with -v) because boot2docker has a read-only filesystem (will get wiped on reboot).

has anyone experienced this socket hangups, and if so, is there any other remedy besides restarting the docker machine?

**Comment by burkostya** [comment]
Hi, unfortunately have no any experience with boot2docker.
I think it's better to ask help on docker forums, not here.

**Comment by japel** [comment]
alright, thanks anyway!
